version: "3.9"

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 10000:10000
    volumes:
        - //var/run/docker.sock:/var/run/docker.sock
        - ../labs:/labs
    restart: always
    networks:
      - heisenberg

networks:
  heisenberg:
    external: true
